Repository openshift/must-gather, pull requests merged in 2019-04, with the labels that each got.

#71 updating reviews
  collection-scripts/OWNERS
Labels: approved, size/XS

#65 Adding the first draft of the CEE Playlist
  collection-scripts/gather
Labels: approved, lgtm, size/M

#73 getting the stroage classes for a cluster
  collection-scripts/gather
Labels: approved, lgtm, size/XS

#74 volumes is not a resource and volumeattachemets are important so adding
  collection-scripts/gather
Labels: approved, lgtm, size/XS

#76 Use full resource name (including group) when retrieving
  pkg/cmd/inspect/util.go
Labels: approved, lgtm, size/XS

#78 make events more powerful
  cmd/openshift-dev-helpers/main.go
  pkg/cmd/events.go
  pkg/cmd/events/event_filter.go
  pkg/cmd/events/events.go
  pkg/cmd/events/io.go
  pkg/util/events.go
Labels: approved, lgtm, size/XL

#79 audit: fix case when response status is nil
  pkg/cmd/audit/io.go
Labels: approved, lgtm, size/S

#80 audit: add top output type
  pkg/cmd/audit/audit.go
  pkg/cmd/audit/io.go
Labels: approved, lgtm, size/L

#81 Filtering sorting
  pkg/cmd/audit/audit_filter.go
  pkg/cmd/events/event_filter.go
  pkg/cmd/events/events.go
  pkg/cmd/events/io.go
  pkg/cmd/events/sort.go
  pkg/util/filtering.go
Labels: approved, lgtm, size/L

#83 Add --by=resource output
  pkg/cmd/audit/audit.go
  pkg/cmd/audit/io.go
Labels: approved, lgtm, size/L

#77 Be explicit about related objects type
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/util.go
Labels: approved, lgtm, size/S

#82 change must-gather image base FROM base to cli
  Dockerfile
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#84 Adding audit and host service log collection with oc
  collection-scripts/gather
  collection-scripts/gather_audit_logs
  collection-scripts/gather_service_logs
Labels: approved, lgtm, size/M
