Repository openshift/must-gather, pull requests merged in 2019-02, with the labels that each got.

#44 add local file support for events
  pkg/cmd/events.go
  pkg/util/events.go
Labels: approved, lgtm, size/M

#51 begin adding unit tests for cmd/inspect
  pkg/cmd/inspect/inspect.go
  pkg/cmd/inspect/inspect_test.go
Labels: approved, lgtm, size/L

#53 remove defaults since we have a truly polymorphic command
  pkg/cmd/inspect/inspect.go
Labels: approved, lgtm, size/S

#50 helper for inspecting cert resources
  cmd/openshift-dev-helpers/main.go
  pkg/cmd/certinspection/certinspection.go
Labels: approved, size/L

#52 fix the namespace resource layout
  .gitignore
  pkg/cmd/inspect/namespace.go
  pkg/cmd/inspect/pod.go
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/util.go
Labels: approved, size/XL

#55 add detail to container-data-gathering errors
  pkg/cmd/inspect/pod.go
Labels: approved, lgtm, size/XS

#58 remove juanvallejo from OWNERS files
  OWNERS
Labels: approved, lgtm, size/XS

#56 add introspection of ca.crt
  pkg/cmd/certinspection/certinspection.go
Labels: approved, lgtm, size/M

#59 Update examples in inspect command & gitignore
  .gitignore
  pkg/cmd/inspect/inspect.go
Labels: approved, lgtm, size/S

#61 dump group and serving info for certs
  pkg/cmd/certinspection/certinspection.go
Labels: approved, lgtm, size/S

#62 elide secret data from sensitive resources
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/route.go
  pkg/cmd/inspect/secret.go
Labels: approved, lgtm, size/L

#63 allow audit filtering
  cmd/openshift-dev-helpers/main.go
  pkg/cmd/audit.go
  pkg/cmd/audit/audit.go
  pkg/cmd/audit/audit_filter.go
  pkg/cmd/audit/io.go
  pkg/util/audit.go
  pkg/util/audit_types.go
Labels: approved, lgtm, size/XL

#64 add collection-scripts to must-gather image
  Dockerfile
  Dockerfile.rhel7
  README.md
  collection-scripts/OWNERS
Labels: approved, lgtm, size/S

#66 restore secret keys which are known to be public
  pkg/cmd/inspect/secret.go
Labels: approved, lgtm, size/S
