Repository openshift/must-gather, pull requests merged in 2019-01, with the labels that each got.

#3 add readme
  README.md
Labels: size/S

#4 Additional improvements
  pkg/cmd/info.go
Labels: size/L

#5 add port-forwarded url request support
  pkg/cmd/info.go
  pkg/util/port_forward.go
  pkg/util/writer.go
Labels: size/L

#11 improve port-forwarding logic
  pkg/cmd/inspect.go
  pkg/util/port_forward.go
Labels: size/M

#13 make binary location normal
  .gitignore
  Makefile
Labels: size/XS

#17 improve directory structure and gathering
  pkg/cmd/inspect.go
Labels: size/L

#18 gate already seen resources
  pkg/cmd/inspect.go
Labels: size/XS

#23 Add dev-helpers and 'events' parser
  .gitignore
  Makefile
  README.md
  dev-helpers/cmd/dev-helpers.go
  pkg/cmd/events.go
  pkg/util/events.go
  vendor/github.com/xeonx/timeago/LICENSE
  vendor/github.com/xeonx/timeago/README.md
  vendor/github.com/xeonx/timeago/timeago.go
  vendor/github.com/xeonx/timeago/timeago_test.go
Labels: size/XL

#25 Fix glide.yaml
  glide.yaml
Labels: size/XS

#28 dev-helper: fix logical bug in audit verb parsing
  pkg/util/audit.go
Labels: size/XS

#22 restructure inspect to handle polymorphic resources
  cmd/must-gather.go
  pkg/cmd/events.go
  pkg/cmd/inspect/inspect.go
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/util.go
Labels: size/XL

#30 add groupName to dir structure
  pkg/cmd/audit.go
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/util.go
Labels: size/S

#31 minor fixes that fix potential ci failures
  pkg/cmd/audit.go
Labels: size/XS

#34 allow more than one arg
  pkg/cmd/inspect/inspect.go
  pkg/cmd/inspect/resource.go
Labels: size/S

#35 limit config/operator.openshift.io data gathering
  pkg/cmd/inspect/inspect.go
  pkg/cmd/inspect/resource.go
Labels: size/M

#36 Creating a default input when --default is supplied
  pkg/cmd/inspect/inspect.go
Labels: size/S

#41 use resource builder to gather all namespace data
  pkg/cmd/inspect/resource.go
Labels: approved, size/M
