Repository openshift/must-gather, pull requests merged in 2019-09, with the labels that each got.

#127 Fixing machine collection
  collection-scripts/gather
Labels: approved, lgtm, size/XS

#128 Bug 1737558: Adding PVC's to Namespace resource collection
  pkg/cmd/inspect/namespace.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#129 generate /must-gather/version file
  collection-scripts/gather
  collection-scripts/version
Labels: approved, lgtm, size/S
