Repository openshift/must-gather, pull requests merged in 2019-06, with the labels that each got.

#95 Bug 1715634: ensure we collect cluster version information
  collection-scripts/gather
Labels: approved, lgtm, size/XS

#96 Bug 1715634: ensure we collect cluster version information
  collection-scripts/gather
Labels: approved, bugzilla/valid-bug, size/XS

#97 Revert "Bug 1715634: ensure we collect cluster version information"
  collection-scripts/gather
Labels: bugzilla/valid-bug

#94 Gather extended network data
  collection-scripts/gather_network_logs
Labels: approved, lgtm, size/M

#93 handle pure negation and don't match empty strings
  pkg/util/filtering.go
Labels: approved, lgtm, size/S

#103 Bug 1722523: fix filenames for collecting versions and metrics
  pkg/cmd/inspect/pod.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#105 Bug 1722548: collection-scripts/gather: add ns/openshift-etcd
  collection-scripts/gather
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#100 Bug 1720321 - must-gather does not collect all non-core CRs in the given namespace
  pkg/cmd/inspect/resource.go
  pkg/cmd/inspect/util.go
Labels: approved, lgtm, size/M
