Repository openshift/must-gather, pull requests merged in 2020-12, with the labels that each got.

#195 Bug 1862643: Collect docker logs from WinEvent log on Windows machines
  collection-scripts/gather_windows_node_logs
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#196 [SDN-1317] Add Data collection for ovn-ipsec encrypted clusters
  collection-scripts/gather_network_logs
Labels: approved, lgtm

#189 NE-356: Add HAProxy config files to must-gather
  collection-scripts/gather
  collection-scripts/gather_haproxy_config
Labels: approved, lgtm

#198 Bug 1906968: Add kubernetes-nmstate resources to must-gather
  collection-scripts/gather
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm
