Repository openshift/must-gather, pull requests merged in 2020-10, with the labels that each got.

#181 Fixed core dumps message
  collection-scripts/gather_core_dumps
Labels: approved, lgtm

#180 gather_network_logs: specfiy sdn container for sdn pods
  collection-scripts/gather_network_logs
Labels: approved, lgtm

#124 adding collection script for validation and mutatin admission webhooks
  collection-scripts/gather
  collection-scripts/gather_admission_webhooks
Labels: approved, lgtm, size/S

#182 Add olm resources to default must-gather
  collection-scripts/gather
  collection-scripts/gather_olm
Labels: approved, lgtm

#183 Bug 1887446: [release-4.5]Backport `gather_core_dumps`
  collection-scripts/gather_core_dumps
  collection-scripts/gather_network_logs
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#136 Split resources to named and groups
  collection-scripts/gather
Labels: approved, lgtm, size/S
