Repository openshift/must-gather, pull requests merged in 2020-09, with the labels that each got.

#172 Bug 1874301: collection-scripts/gather_network_logs: add detailed status for interfaces
  collection-scripts/gather_network_logs
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#173 Bug 1877428: Update gather_core_dumps to get raw coredump files
  collection-scripts/gather_core_dumps
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#174 Bug 1877428: Update gather_core_dumps collection of debug pod's name, clean up resources
  collection-scripts/gather_core_dumps
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#177 Bug 1877428: Increase gather_core_dump robustness after seeing some CI issues
  collection-scripts/gather_core_dumps
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#176 Bug 1861746: force disk flush after collecting audit logs
  collection-scripts/gather
  collection-scripts/gather_audit_logs
  collection-scripts/gather_core_dumps
  collection-scripts/gather_etcd
  collection-scripts/gather_network_logs
  collection-scripts/gather_network_ovn_trace
  collection-scripts/gather_service_logs
  collection-scripts/gather_windows_node_logs
  collection-scripts/openshift-must-gather
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#175 Bug 1868794: Gather OVS logs from host
  collection-scripts/gather_network_logs
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#179 Bug 1877428: Update `gather_core_dumps` to fix unexpected behavior in CI
  collection-scripts/gather_core_dumps
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#144 Bug 1862426: gather the audit logs for oauth apiserver
  collection-scripts/gather
  collection-scripts/gather_audit_logs
  collection-scripts/gather_service_logs
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/M
