Repository openshift/must-gather, pull requests merged in 2020-08, with the labels that each got.

#160 Bug 1849244: [release-4.5]Trace ovn processing in cluster
  collection-scripts/gather_network_ovn_trace
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#165 Separate Linux and Windows node log collection
  collection-scripts/gather
  collection-scripts/gather_network_ovn_trace
  collection-scripts/gather_service_logs
  collection-scripts/gather_windows_node_logs
Labels: approved, lgtm

#168 Gather more storage objects
  collection-scripts/gather
Labels: approved, lgtm

#169 Bug 1868716: Implements more log collection for Openshift networking
  collection-scripts/gather_core_dumps
  collection-scripts/gather_network_logs
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
