Repository openshift/must-gather, pull requests merged in 2022-05, with the labels that each got.

#299 gather_profiling_node: correctly manage NotReady Nodes
  collection-scripts/gather_profiling_node
Labels: lgtm, approved

#297 Add SR-IOV gather script
  collection-scripts/gather
  collection-scripts/gather_sriov
Labels: lgtm, approved

#300 Bug 2023295: Add networking resources
  collection-scripts/gather_network_logs
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#296 Bug 1999529: Filter disabled resources in inspection to proceed others
  collection-scripts/gather
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#303 Bug 2023295: fix getting deployment name
  collection-scripts/gather_network_logs
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#306 Bug 2090730: Adds collection of Multus log files
  collection-scripts/gather_multus_logs
  collection-scripts/gather_network_logs
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#305 Bug 2091658: Improve the sriov gather script
  collection-scripts/gather_sriov
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-unspecified
