Repository openshift/must-gather, pull requests merged in 2022-06, with the labels that each got.

#313 Bug 2097346: Updates how gether_monitoring obtains SA token
  collection-scripts/gather_monitoring
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#308 [release-4.9] Bug 2092265: Add networking resources
  collection-scripts/gather_network_logs
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#315 Stop collecting Docker logs on Windows instances
  collection-scripts/gather_windows_node_logs
Labels: lgtm, approved
