Repository openshift/must-gather, pull requests merged in 2023-06, with the labels that each got.

#363 OCPBUGS-14025: Add gather_vsphere
  collection-scripts/gather
  collection-scripts/gather_vsphere
Labels: lgtm, approved, px-approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#365 OCPBUGS-14984: Collect Mellanox firmware information
  collection-scripts/gather_sriov
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#353 Gather ostree related bits
  collection-scripts/gather_service_logs
Labels: lgtm, approved

#361 MCO-608: Gather MCO's on-disk configs from degraded nodes
  collection-scripts/gather
  collection-scripts/gather_machineconfig_ondisk
Labels: lgtm, approved, jira/valid-reference

#367 Assert that only one subscription exists
  collection-scripts/gather_ingress_node_firewall
  collection-scripts/gather_metallb
  collection-scripts/gather_network_observability
  collection-scripts/gather_nmstate
  collection-scripts/gather_sriov
Labels: lgtm, approved

#368 Create a generic "get_operator_ns" util function
  collection-scripts/common.sh
  collection-scripts/gather_ingress_node_firewall
  collection-scripts/gather_metallb
  collection-scripts/gather_network_observability
  collection-scripts/gather_nmstate
  collection-scripts/gather_sriov
Labels: lgtm, approved
