Repository openshift/must-gather, pull requests merged in 2023-10, with the labels that each got.

#385 OCPBUGS-19761: Removed workload partitioning annotation from ppc script
  collection-scripts/gather_ppc
Labels: lgtm, approved, ok-to-test, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#386 ppc: explicitly add RuntimeClass to gathered resources
  collection-scripts/gather_ppc
Labels: lgtm, approved

#387 sriov: Clean up `ip netns` output
  collection-scripts/common.sh
  collection-scripts/gather_sriov
Labels: lgtm, approved

#369 gather_sriov: Fix typos and collect SRIOV cache at /var/lib/cni/sriov
  collection-scripts/gather_sriov
Labels: lgtm, approved

#390 OCPBUGS-20391: Revert "Add must gather script for network observability"
  collection-scripts/gather
  collection-scripts/gather_network_observability
Labels: lgtm, approved, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#380 machineconfig: always gather MCS-served config
  collection-scripts/gather_machineconfig_ondisk
Labels: lgtm, approved
