Repository openshift/must-gather, pull requests merged in 2024-11, with the labels that each got.

#463 MCO-1418: Add collection for MOSC and MOSB
  collection-scripts/gather_ppc
Labels: lgtm, approved, jira/valid-reference

#459 OCPBUGS-42835: Removes reference to gather_multus_logs in 4.17
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#465 OCPBUGS-44857: Separate resources with comma to fix malformed inspect
  collection-scripts/gather
Labels: lgtm, approved, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
