Repository openshift/must-gather, pull requests merged in 2024-10, with the labels that each got.

#435 RFE-5765: Collect etcd object count
  collection-scripts/gather_etcd
Labels: lgtm, approved, jira/valid-reference

#445 OCPBUGS-42835: [Release-4.17] Network logs collection: skip unready nodes
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#449 OCPBUGS-43056: Open [Release-4.16] Multus is now a Pod and will be captured by normal
  collection-scripts/gather_multus_logs
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#450 OCPBUGS-43057: [Relase-4.15] Multus is now a Pod and will be captured by normal
  collection-scripts/gather_multus_logs
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#451 OCPBUGS-43058: [Backport 4.14] Multus is now a Pod and will be captured by normal
  collection-scripts/gather_multus_logs
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#458 OCPBUGS-42679: Support gathering IPsec data
  collection-scripts/gather_network_logs_basics
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
